language: python
sudo: required # needed for test_become
dist: xenial
python:
    - "2.7"
    - "3.6"
env:
    - TOXENV=ansible_v25
    - TOXENV=ansible_v26
    - TOXENV=ansible_v27
    - TOXENV=ansible_devel
install:
    - pip install -r test-requirements.txt
script:
    - tox
before_script:
    - TOXENV=lint tox
after_success:
    - TOXENV=coveralls tox
addons:
  apt_packages:
    - pandoc
